### ISSUE TITLE
Add afc GitHub topic

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#1]
It would be great to add the [afc GitHub topic](https://github.com/topics/afc) to this repository to make it consistent with other [asus-fan-control](https://github.com/dominiksalvet/asus-fan-control) related projects.

**Comment by Greifent** [comment]
Yeah, but I don't know how to add it

**Comment by dominiksalvet** [comment]
Yeah, that's fine! :smile: [This link](https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository) should help you. Let me know if you need further assistance... :rocket:

**Comment by Greifent** [comment]
Thanks, added to afc
