### ISSUE TITLE
Not working with UBUNTU 18.04

### ISSUE THREAD

**Issue by ugurkanates** [Greifent/afc-gui#10]
```
Traceback (most recent call last):
  File "./afc-gui", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```
`sudo apt-get install -y python-gobject

`I did this , still didnt work

**Comment by Greifent** [comment]
Hi, try using this `sudo apt-get install python3-gi` if it still don't work let me know and I wil install a VM with Ubuntu 18.04 to try it out.

**Comment by ugurkanates** [comment]
I did , still couldn't make it work

**Comment by dominiksalvet** [comment]
BTW guys I have Ubuntu 18.04 and it is working perfectly fine for me (or at least it was when I tried it).

> I did , still couldn't make it work

Does it still end up with the same error message?

**Comment by Greifent** [comment]
Hi, I've done a fresh install of Ubuntu 18.04, I'll let you know
BTW, try using the file testing.py until the problem is solved, it have the same functionality without the asus-fan-control part.

**Comment by Greifent** [comment]
I have tested it on a fresh install and it work, please post the error message, and does it says that python3-gi is installed?

**Comment by ugurkanates** [comment]
This is the error I'm having. As can be seen from screenshot I tried installation of that package as well.
![img](https://i.ibb.co/dJrHCh1/Screenshot-from-2020-06-28-20-58-14.png)

**Comment by Greifent** [comment]
That is very strange, what i can tell you to try is: `sudo apt-get install pkg-config libcairo2-dev gcc python3-dev libgirepository1.0-dev` then `pip3 install gobject PyGObject` Source: [here](https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python)

**Comment by ugurkanates** [comment]
I'm afraid problem lies with GNOME and PyGobject package. It can't be installed via pip 20.0> versions. Such ones ship with ubuntu 18 04 lts or more.

Closing this but maybe should be noted as dependencies.

**Comment by Greifent** [comment]
It might be that, I still can't explain why it work on my machine and not on yours. I'll continue to try discovering why. I'll keep you update

**Comment by Greifent** [comment]
BTW, after installing `gobject & PyGObject` what do you get? Can you install them or you have other issues?
