### ISSUE TITLE
Start using Git tags

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#11]
**Is your feature request related to a problem? Please describe.**
In default, GitPack picks the latest tag (release) to install for end users. If there are no tags (which is this repository's case), GitPack uses the latest commit of a default branch (master branch), which may not be always stable.

Let's say there are two tags – 1.2.2 and 1.2.3 (most recent). When we use `gitpack install github.com/Greifent/afc-gui`, it will use 1.2.3 tag. We can explicitly say  which version to use as follows `gitpack install github.com/Greifent/afc-gui=1.2.2`. Or even if there are tags, we can use the latest commit – `gitpack install github.com/Greifent/afc-gui=master`. GitPack is clever enough to update/downgrade between versions.

**Describe the solution you'd like**
Once the current state of the Git repository is considered a new version, add an associated Git tag. E.g., use `git tag 1.2.3` and then you need to push it explicitly – `git push origin 1.2.3`. Once it is pushed, it will appear on GitHub and you can create a [release](https://github.com/Greifent/afc-gui/releases) (which is a GitHub thing) from it. That should do it.

**Comment by Greifent** [comment]
Oh, I did not know I could do that, thanks!

**Comment by Greifent** [comment]
It should be done with version 1.3.0, let me know if it does not work!

**Comment by dominiksalvet** [comment]
Good, thanks! It works. Anyway, try for yourself ‒ `gitpack status github.com/Greifent/afc-gui`.
