### ISSUE TITLE
Temps Presets

### ISSUE THREAD

**Issue by Greifent** [Greifent/afc-gui#12]
Hi, @dominiksalvet I'm currently working on a preset choice (ex 100%, 75% etc); I've created a xlsx file with the presets and the temperature to set. If you could take a look and let me know about those temperatures.
Here is the file: [Presets.xlsx](https://github.com/Greifent/afc-gui/files/5183581/Presets.xlsx)
Thank you!
Here there is also another file with some info for the presets: [Info_on_presets.docx](https://github.com/Greifent/afc-gui/files/5183611/Info_on_presets.docx)

**Comment by dominiksalvet** [comment]
Hello @Greifent, it is your afc extension and hence it is completely up to you which features are implemented and how (as long as it does not affect my afc projects). To be honest, I do not have time right now as I am finally finishing my bachelor's studies. Sorry but I cannot help here.

I personally did not want to implement this feature directly into afc (see https://github.com/dominiksalvet/asus-fan-control/issues/52), but it may be a good idea to ask the OP of the mentioned issue (@ezio-ac).

**Comment by Greifent** [comment]
Ok, no problem, good luck with your studies!
That part wasn't going to be implemented on your part, it will stay on mine. I had only a doubt on the temps inside that file.
