### ISSUE TITLE
Move to new GitPack 1.0.0 format

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#13]
Hello @Greifent! :wave:

For over a year I have been working on a stable release of GitPack, [version 1.0.0](https://github.com/dominiksalvet/gitpack/projects/1?fullscreen=true). After all the work and polishing details, I think that the new GitPack is very close and I expect no further code-related changes. Since you are currently the only developer (except me), who uses GitPack in their projects, I wanted to let you know this fact and created this issue to track the GitPack 1.0.0 transition in afc-gui. Once GitPack 1.0.0 is out, a new AFC version (with GitPack 1.0.0 format) will be released as well. Please note that GitPack 1.0.0 is incompatible with lower versions.

So what changed from the developer's point of view? One thing basically. The `.gitpack` directory is now `.install` directory with a simplified structure. Also, GitPack 1.0.0 no longer uses `map` file and all (un)installation is done within executable files (it may be Shell scripts, Python, pretty much anything). The complete list of changes is in [the changelog](https://github.com/dominiksalvet/gitpack/blob/master/changelog.md). Grap some coffee to read through it! :coffee: :smiley: 

The GitPack master branch contains the most recent code changes, while the [update-md-files branch](https://github.com/dominiksalvet/gitpack/tree/update-md-files) contains MD files prepared for GitPack 1.0.0 (use this branch for getting information about new GitPack). If you read the MD files in the update-md-files branch, you will be able to switch your repository to GitPack 1.0.0 yourself. Once 1.0.0 is released, I will also have prepared a transition guide for users of GitPack packages (end users of our programs). The packages must be uninstalled using 0.7.0 and installed back using 1.0.0. Please, watch GitPack for releases so that you won't miss the release. :rocket: 

So what I propose for you to do now? Switch afc-gui to the new GitPack 1.0.0 format and keep it in the master branch (do not worry, it should be easy for afc-gui). Do not release any versions before GitPack 1.0.0 is out so that GitPack 0.7.0 still uses a compatible afc-gui version. When 1.0.0 is out, the 0.7.0 will become deprecated. You can get inspired by my [GitPack repositories](https://github.com/topics/gitpack), which are already prepared for GitPack 1.0.0 the same way -- waiting for the release in the master branch.

Should you have any issues/questions, let me know! :octocat:

**Comment by Greifent** [comment]
Hi, thanks for the information, will definitely look at that, unfortunately i'm very busy with university now. I will do the update as soon as possible, hope to do it before the end of the month.
Edit: I've taken a quick look at your afc to see how the new process work, in my case I just need to create a bash script that copies the necessaries files right?

**Comment by dominiksalvet** [comment]
> I've taken a quick look at your afc to see how the new process work, in my case I just need to create a bash script that copies the necessaries files right?

Yes. It will be very similar to [this](https://github.com/dominiksalvet/nconv/commit/b986a4fa7a2c48a5a3dbfcd0a1762940b1e90213) I guess. :smile:

**Comment by Greifent** [comment]
yeah, thanks. I'll keep the issue open so I can find it easly

**Comment by dominiksalvet** [comment]
Ok. In case you will not make it until the 1.0.0 release, would it be okay to release the new GitPack anyway? It means that AFC newcomers would not be able to install afc-gui alongside until you release a new version...

**Comment by Greifent** [comment]
I honestly hope to make it in a few days, if I cant do that I'll update the README.md saying that temporarily they need to manually install the program

**Comment by Greifent** [comment]
It should be done

**Comment by dominiksalvet** [comment]
Great! :rocket:  We can leave this issue open until GitPack 1.0.0 is released and new afc-gui version is tested with it...

**Comment by dominiksalvet** [comment]
Okay, so GitPack 1.0.0 is out!! You may release the new version and try it out... :rocket: Good luck with the studies BTW. :crossed_fingers: Once done, feel free to close this issue.

**Comment by Greifent** [comment]
Hopefully it should work, at least it work on mine. I'll update the readme file.
Studies are going on, its pretty hard but im going

**Comment by dominiksalvet** [comment]
Great! :clap: It is working on my device as well!
