### ISSUE TITLE
afc wont start

### ISSUE THREAD

**Issue by theguy000** [Greifent/afc-gui#15]
**Describe the bug**
afc-gui wont start and says 
> gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/share/afc-gui/MAINGUI.glade”: No such file or directory (4)

**To Reproduce**
1. Go to 'afc-gui'
2. See error

**Expected behavior**
Traceback (most recent call last):
  File "/usr/bin/afc-gui", line 188, in <module>
    builder.add_from_file(pathglade)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/share/afc-gui/MAINGUI.glade”: No such file or directory (4)

**Screenshots**

**Additional context**
...................................................................
You should never use relative paths to files, so you need to figure out an absolute path at runtime usually by defining an install prefix at build time. Also ideally you use GResources to simplify the process and improve performance.

An example would be something like this:

https://github.com/pithos/pithos/blob/master/bin/meson.build
https://github.com/pithos/pithos/blob/master/bin/pithos.in#L40-L41
See also: https://developer.gnome.org/gio/stable/GResource.html

You can get more help if you stop by #newcomers on ircs://irc.gimp.net or https://riot.im/app/#/room/#gimpnet#newcomers:matrix.org

I tried to google the [answer]( https://stackoverflow.com/questions/46415463/loading-glade-file-in-gnome-builder). But it was too geeky for me.
............................................................
Linux Asus-s451lb 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux

**Comment by Greifent** [comment]
Hi, have you installed the program using gitpack or manually? I just tried with gitpack and its working fine.
I'll take a look at what you suggested, this is the only project I've done using GTK so unfortunately my experience is limited

**Comment by dora-07** [comment]
Actually I had the same problem
So the problem is the readme file says to move the afc-gui and MAINGUI.glade to /usr/bin and when executed the code checks for the MAINGUI.glade file in the /usr/share directory

Solution:
Just edit the afc-gui file with a text editor and set 
pathglade = "/usr/bin/MAINGUI.glade" (or where ever you have moved the file to)

Hope this helps.

**Comment by Greifent** [comment]
Thanks @kniloy07, that was a error on the readme, i didnt noticed it, i'm going to update the readme with the correct path, thanks for bringing that up, it will say /usr/share/afc-gui
