### ISSUE TITLE
ASUS GL502VS not reporting

### ISSUE THREAD

**Issue by cenkozk** [Greifent/afc-gui#16]
**Describe the bug**
ASUS GL502VS is not reporting the CPU Temp and the model info. If I launch the afc-gui with the sudo command the gui reports the model info but the CPU Temp is not still reporting.

**To Reproduce**
1. Launch the afc-gui

**Expected behavior**
Expected to report the CPU Temp and the model info.

**Screenshots**
![2022-06-04_09-59](https://user-images.githubusercontent.com/55915851/171988765-8357c6d2-24f1-4d25-a254-ce65b4819db4.png)

**Additional context**
-I've already installed the CPU-temperature-monitor.
-Afc works fairly well even though CPU temp is not working on gui.

**Comment by Greifent** [comment]
Hi, the gui is supposed to be run as sudo to allow asus-fan-control to work, as per the Cpu temperature I suggest to try and run `cpu-temperature-monitor` on a terminal and see if it reports something. Unfortunately right now I don't have a computer on hand I will probably have one in 4 or so hours, I'll try to see better then.

**Comment by Greifent** [comment]
Disregard the command I said to run before, the correct one is `get_current_cpu_temp`, you should get a result similar to this: 
```
pc@pop-os:~$ get_current_cpu_temp 
2022-06-04 14:27:18.086191, 55.125 C°, 131.225 F°
```

**Comment by cenkozk** [comment]
Thank you for helping me out, the ```get_current_cpu_temp``` command was the issue. I uninstalled the pip package and cleared the cache then installed it again. Now it works great.

**Comment by Greifent** [comment]
That's good to hear, happy it works!
