### ISSUE TITLE
No CPU temp

### ISSUE THREAD

**Issue by mews-se** [Greifent/afc-gui#17]
**Describe the bug**
afc-gui can't display cpu temp despite having all dependencies. ux430ua

**Screenshots**
![Screenshot at 2022-06-25 00-45-51](https://user-images.githubusercontent.com/58894405/175749116-c8d618e3-59df-4495-94c9-31363e393609.png)

**Comment by Greifent** [comment]
Hello, try running the `get_current_cpu_temp` command and see what it reports

**Comment by mews-se** [comment]
> Hello, try running the `get_current_cpu_temp` command and see what it reports

`Traceback (most recent call last):
  File "/usr/local/bin/get_current_cpu_temp", line 8, in <module>
    sys.exit(get_current_cpu_temp())
  File "/usr/local/lib/python3.8/dist-packages/AvgCpuTemp/avg_cpu_temp.py", line 25, in get_current_cpu_temp
    for stamp, value_in_c in itertools.islice(zip(timestamp, sensor), 1):
  File "/usr/local/lib/python3.8/dist-packages/AvgCpuTemp/avg_cpu_temp.py", line 14, in __next__
    return psutil.sensors_temperatures()['k10temp'][0][1]
KeyError: 'k10temp'`

**Comment by Greifent** [comment]
That seems to be an issue with the dependency, would suggest trying to reinstall, and if its still present try to open an issue on the CPU-temperature-monitor github [here](https://github.com/urosjevremovic/CPU_temperature_checker), even if the project seems no longer mantained

**Comment by notquite28** [comment]
i have the same issue :(

**Comment by Greifent** [comment]
That is weird, i guess that reinstalling the dependency didnt help, since its the 3rd time issues with this dependency has been reported (probably the fact that the last update was 4 years ago doesnt help), ill look into another way to have the temperature displayed.

**Comment by Greifent** [comment]
Ok so, I've removed the dependency, unfortunately for now how it works it's the same, I'm still trying to find another solution, it's turning out more difficult than I thought

**Comment by Greifent** [comment]
Quick update, probably found a way, if you could please update to version 2.0.1 (if you are using gitpack just re-run the install command) and let me know if it's fixed or not, thanks!

**Comment by notquite28** [comment]
what about the afc-gui-gtk4.cmb file? does it need to moved somewhere? also showingthis error 
![image](https://user-images.githubusercontent.com/43907678/178115848-c4f72c6d-607c-4c46-b94c-79dc9c76d146.png)

**Comment by Greifent** [comment]
that file is not necessary, and my bad, forgot to change a variable, ill fix it now

**Comment by Greifent** [comment]
Should be fixed

**Comment by notquite28** [comment]
seems to work fine. Thanks for the quick update
![image](https://user-images.githubusercontent.com/43907678/178116889-dd85db70-1b34-403f-afe7-bd773890561d.png)

**Comment by Greifent** [comment]
No worries, ill wait for @mews-se to report then ill close the issue

**Comment by notquite28** [comment]
cd afc-gui/src/
sudo rm /usr/bin/afc-gui
sudo rm -r /usr/share/afc-gui/
sudo rm /usr/share/applications/afc-gui.desktop


sudo cp afc-gui /usr/bin/
sudo mkdir /usr/share/afc-gui
sudo cp afc-gui-gtk4.ui /usr/share/afc-gui/
sudo cp afc-gui.desktop /usr/share/applications/


also can you add these commands, it took my autistic brain quite some time to understand the instructions lol

**Comment by Greifent** [comment]
Yea sure, ill add them now

EDIT: I've updated the README.md

**Comment by mews-se** [comment]
Thanks for a quick fix. Unfortunatly now I'm stuck needing GTK 4 so it doesn't run at all :)

**Comment by Greifent** [comment]
I didnt thought of that possible issue, i can pass you the gtk3 version, i still have it, just need to update the temperature stuff

**Comment by Greifent** [comment]
I uploaded the gtk3 version here https://github.com/Greifent/afc-gui-gtk3/

**Comment by mews-se** [comment]
Yay. Thanks!

![Screenshot at 2022-07-09 21-54-53](https://user-images.githubusercontent.com/58894405/178120777-4236f926-f845-499f-ac9c-b95122f38149.png)

**Comment by Greifent** [comment]
No worries, i will close the issue now
