### ISSUE TITLE
Not working on Linux Mint

### ISSUE THREAD

**Issue by Blaarkies** [Greifent/afc-gui#18]
**Describe the bug**
With a fresh install of Linux Mint, I am trying to get this running.

**To Reproduce**
1. Install using `user@machine:~/Downloads$ sudo gitpack install https://github.com/Greifent/afc-gui.git`
2. Input password, and get this output
```
[sudo] password for user:         
>>> running install for https://github.com/Greifent/afc-gui.git
local repository fresh
reading status database
using automatic candidate version
<<< already installed
```
3. Run using
```
user@machine:~/Downloads$ afc-gui
```
```
Traceback (most recent call last):
  File "/usr/bin/afc-gui", line 8, in <module>
    gi.require_version('Gtk', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_afc-gui.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/afc-gui", line 8, in <module>
    gi.require_version('Gtk', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
user@machine:~/Downloads$ 
```

**Expected behavior**
The GIU should open up

**Comment by Blaarkies** [comment]
My bad, GTK4 version not working on Linux Mint 20

GTK3 version works

**Comment by S0me1-dev** [comment]
@Blaarkies , hello. Could you provide plz how to run it on debian with gtk 4.0 got same trouble on Kali 
plz help - fan gone mad even in manual silent mode by hotkeys ))

**Comment by Blaarkies** [comment]
Unfortunately I didn't get everything working, so opted for an LTSC os instead

**Comment by Greifent** [comment]
> Unfortunately I didn't get everything working, so opted for an LTSC os instead

What didn't you manage to get working?

**Comment by Greifent** [comment]
> @Blaarkies , hello. Could you provide plz how to run it on debian with gtk 4.0 got same trouble on Kali 
> plz help - fan gone mad even in manual silent mode by hotkeys ))

Could you please tell me what version of Kali/debian are you using? I'll do some tests this afternoon when I get home from work

**Comment by Blaarkies** [comment]
> What didn't you manage to get working?

I have a Zephyrus S17 (2019), and could not get control over the fans. It wasn't in the list of supported devices though, so no surprises really.

The GUI worked, and loaded up without issues, but it didn't change fan speeds (i'm guessing the driver part didn't respond correctly)

**Comment by Greifent** [comment]
> > What didn't you manage to get working?
> 
> I have a Zephyrus S17 (2019), and could not get control over the fans. It wasn't in the list of supported devices though, so no surprises really.
> 
> The GUI worked, and loaded up without issues, but it didn't change fan speeds (i'm guessing the driver part didn't respond correctly)

That is probably why, unfortunately I can't help you with that, you'll have to ask support on the [asus-fan-control](https://github.com/dominiksalvet/asus-fan-control) project page

**Comment by S0me1-dev** [comment]
> > @Blaarkies , hello. Could you provide plz how to run it on debian with gtk 4.0 got same trouble on Kali 
> > plz help - fan gone mad even in manual silent mode by hotkeys ))
> 
> Could you please tell me what version of Kali/debian are you using? I'll do some tests this afternoon when I get home from work 

fx505dd Asus tuf , and latest Kali Linux 
Debian 6.1.12-1kali2
6.1.0-kali5-amd64

**Comment by Greifent** [comment]
> > > @Blaarkies , hello. Could you provide plz how to run it on debian with gtk 4.0 got same trouble on Kali
> > > plz help - fan gone mad even in manual silent mode by hotkeys ))
> > 
> > 
> > Could you please tell me what version of Kali/debian are you using? I'll do some tests this afternoon when I get home from work
> 
> fx505dd Asus tuf , and latest Kali Linux Debian 6.1.12-1kali2 6.1.0-kali5-amd64

I couldn't get the gtk4 application to run, but the [gtk3](https://github.com/Greifent/afc-gui-gtk3) version worked fine after install, I suggest you try that
