### ISSUE TITLE
No module named 'psutil'

### ISSUE THREAD

**Issue by KoorbNotsyor** [Greifent/afc-gui#19]
Running afc-gui on Ubuntu 24.04 produces Python traceback ending in the message "ModuleNotFoundError: No module named 'psutil'".

I don't have pip on the laptop , I haven't set up python yet - it's a new install.

installed python3-psutil and all OK now

**Comment by Greifent** [comment]
> Running afc-gui on Ubuntu 24.04 produces Python traceback ending in the message "ModuleNotFoundError: No module named 'psutil'".
> 
> 

Hello, did you try ```pip install psutil``` to install the module?
