### ISSUE TITLE
Make testing.py executable

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#2]
The [*testing.py*](https://github.com/Greifent/afc-gui/blob/master/testing.py) script does not have the execution permission and hence it is not runnable out of the box. `chmod +x` will gladly fix it. :hammer:

**Comment by Greifent** [comment]
Oh, I forgot to set that, I'm doing it now

**Comment by Greifent** [comment]
After an hour i managed to upload the executable version

**Comment by dominiksalvet** [comment]
Great, you could have closed the issue as it has been effectively resolved. I will do so.
