### ISSUE TITLE
Add image to README.md

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#3]
It would be great to add a demonstration image of this program running to the [*README.md*](https://github.com/Greifent/afc-gui/blob/master/README.md) so that people know what to expect. This image can also motivate others to download afc-gui. :tada:

> Feel free to add the image once you do not expect changing the program's design for a while. **It does not have to be done right now** so that the image is not changed every other commit or so, which is not so good for Git repositories. :smile:

**Comment by Greifent** [comment]
I'm still adding thing on an almost daily base, as soon as I'm on a good point I'll add an image.

**Comment by dominiksalvet** [comment]
Glad to hear that! Feel free to close this issue now or once you will have added them.

**Comment by Greifent** [comment]
I'll leave it open, so I will remember to do that

**Comment by Greifent** [comment]
I added the photos, those shouldn't change for a wile; I'm closing the issue

**Comment by dominiksalvet** [comment]
Great! One little note - it would be great to have the selection window depicted while located in the *~/.local/share/afc-gui/temperaturesPreset* directory where default presets are actually placed as it is not a standard place and it can help many people.

**Comment by Greifent** [comment]
Yes I was thinking about it, I need to figure out how to do it

**Comment by dominiksalvet** [comment]
> Yes I was thinking about it, I need to figure out how to do it

Install afc-gui using GitPack? :smile: It will create the directory for you by your GitPack map. To show hidden files (file names beginning with a dot) use Ctrl+H or right click and Show Hidden Files.

BTW, good job with README.md! It is good to see it continuously improving! :+1:

> Did you know that GitPack has its [own GitHub topic](https://github.com/topics/gitpack), which you can use as well. You can also add other to make your repository more reachable. :rocket:

**Comment by Greifent** [comment]
If I understood, you are suggesting that the pick file dialog open directly in the ~/.local/share/afc-gui/temperaturesPreset directory, I need to figure out how to open that window in that directory, I have installed on my machine using gitpack to see if it work fine, and the dialog open in the ~ directory

**Comment by Greifent** [comment]
Thanks, it took me 30 minutes to load the images. I'm happy that you like it

**Comment by dominiksalvet** [comment]
> If I understood, you are suggesting that the pick file dialog open directly in the ~/.local/share/afc-gui/temperaturesPreset directory, I need to figure out how to open that window in that directory, I have installed on my machine using gitpack to see if it work fine, and the dialog open in the ~ directory

Nope, you are talking about something else. But that would be a great idea as well to have it opened in that directory by default so that people do not have to find it themselves.

What I was talking about, however, is to take a new screenshot of the file selection window while being in that directory and replace the current README.md image with it. Only to show people where to look for these presets. But opening that file dialog directly in that directory by default would make things even easier! :rocket:

**Comment by Greifent** [comment]
Oh, yeah that make sense, I didn't thought about that

**Comment by Greifent** [comment]
Done that. For the other one I need to look how to do that

**Comment by dominiksalvet** [comment]
Good job! :+1: :clap:
