### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#4]
Since your repository does not contain a license file, you retain all rights and do not share any of them with others. Once you [attach a license](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) to this repository, you will say users exactly what they can and cannot do with your software/source code.

I suggest using an open-source license - the **best would be the MIT License** as the rest of asus-fan-control software is licensed under the same license. Keep in mind that even in case of using such a permissive license like MIT, **you still will be the copyright owner**. :copyright: 

What do you think? :scroll:

**Comment by Greifent** [comment]
Good idea

**Comment by Greifent** [comment]
Added
