### ISSUE TITLE
Active temperatures are not refreshed

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#7]
Once temperatures are changed in afc-gui using a button, the active temperatures on the top of the window are not refreshed with new temperature values. It would be great if they refresh in those cases.

**Comment by Greifent** [comment]
I know that, I'm currently trying to do that, for now you need to restart the window

**Comment by dominiksalvet** [comment]
You do not need to work on my issues immediately if you have school or so. This is nothing serious in terms of afc-gui stability and reliability. :relaxed: I just wanted to create them so that I do not need to remember it.

**Comment by Greifent** [comment]
Yes, I know, in fact I'm going pretty slow, in a few weeks I have also the test to enter the Uni, so the update will be basically zero, except for important problems

**Comment by dominiksalvet** [comment]
Great! Hope you will get to the university you want! :crossed_fingers:

**Comment by Greifent** [comment]
I've found a way to update the temperatures, it will be in the next update
Edit: I've added that functionality
