### ISSUE TITLE
Add gitpack GitHub topic

### ISSUE THREAD

**Issue by dominiksalvet** [Greifent/afc-gui#9]
Similarly to #1, it would be great to add the [gitpack GitHub topic](https://github.com/topics/gitpack) to this repository to make it consistent with other [gitpack](https://github.com/dominiksalvet/gitpack) related projects.

---

Thank you for developing and maintaining this project! :heart: :rocket: Hope you are doing fine with the university stuff and so! :smile:

**Comment by Greifent** [comment]
Added to the git-pack. I'm doing pretty well, a lot of stress unfortunately. I'll continue the development during the summer

**Comment by dominiksalvet** [comment]
> Added to the git-pack.

Thank you. :smile:

> I'm doing pretty well, a lot of stress unfortunately. I'll continue the development during the summer

Glad to hear that! :+1: I bet the stress will fade out eventually! :smile: :fog:
